#!/usr/bin/env bash

# secrethubwarden
#
# Copy secrets from Bitwarden to GitHub repository secrets
#
# Source: https://github.com/cstuder/secrethubwarden
#
# License: MIT

set -o errexit   # abort on nonzero exitstatus
set -o nounset   # abort on unbound variable
set -o pipefail  # don't hide errors within pipes

# TODO Check if bw is installed

# TODO Check if gh is installed

# TODO Check if jq is installed

# TODO Check if bw is logged in

# TODO Check if gh is logged in

# TODO Read in .secrethubwardenfile

# TODO Validate that all Bitwarden secrets exists and are unique

# TODO Update secrets on GitHub
