on: push

name: "Output secrets to the log"

jobs:
  outputsecrets:
    runs-on: ubuntu-latest
    steps:
      - name: Echo secret
        env: # Or as an environment variable
          MY_SECRET_PASSWORD: ${{ secrets.MY_SECRET_PASSWORD }}
        run: |
          echo "Part 1: ${MY_SECRET_PASSWORD:0:8}"
          echo "Part 2: ${MY_SECRET_PASSWORD:8:}"
