on: push

name: "Output secrets to the log"

jobs:
  outputsecrets:
    runs-on: ubuntu-latest
    steps:
      # Note: GitHub automatically replaces outputted secrets in the log with ***. To circumvent this, we output the secret in two parts
      - name: Echo secret password
        env:
          MY_SECRET_PASSWORD: ${{ secrets.MY_SECRET_PASSWORD }}
        run: |
          echo "Part 1: ${MY_SECRET_PASSWORD:0:8}"
          echo "Part 2: ${MY_SECRET_PASSWORD:8}"

      # Ditto for the multiline secret, we output it line by line.
      - name: Echo secret note
        env:
          MY_SECRET_NOTE: ${{ secrets.MY_SECRET_NOTE }}
        run: |
          while IFS= read -r line; do
            echo "> $line"
          done <<< "$MY_SECRET_NOTE"
